services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia # optional (if you have GPU)
              count: all
              capabilities: [ gpu ]
    command: >
      ollama pull deepseek-r1 &&
      ollama pull llama3.3 &&
      ollama pull gemma2 &&
      ollama pull llava
    volumes:
      - ollama-core:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3456:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    depends_on:
      - ollama # wait ollama service ready

volumes:
  ollama-core:
  open-webui:
